### ISSUE TITLE
Plugin Crashes on Every Version

### ISSUE THREAD

**Issue by THolleyZen** [devoteamgcloud/terraform-provider-looker#85]
**Version:** 0.3.0 - 0.4.1-beta

**Problem:** When attempting to create a `looker_alert` using the `terraform apply` the plugin crashes. I have tested this behavior on all of the versions in the range above. Below is the crash information.
```
looker_alert.default: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with looker_alert.default,
│   on alerts.tf line 1, in resource "looker_alert" "default":
│    1: resource "looker_alert" "default" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-looker_v0.4.0 plugin:

panic: interface conversion: interface {} is string, not *string

goroutine 61 [running]:
github.com/devoteamgcloud/terraform-provider-looker/internal/provider.resourceAlertsCreate({0xed66b8, 0xc000300cc0}, 0xc86aa0?, {0xc24220?, 0xc0002a24e0?})
	github.com/devoteamgcloud/terraform-provider-looker/internal/provider/resource_alert.go:234 +0x18c7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00043a0e0, {0xed66f0, 0xc0002869f0}, 0xd?, {0xc24220, 0xc0002a24e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00043a0e0, {0xed66f0, 0xc0002869f0}, 0xc0001668f0, 0xc000165100, {0xc24220, 0xc0002a24e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000af320, {0xed6648?, 0xc0004c8480?}, 0xc0004d63c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000fd220, {0xed66f0?, 0xc0002861e0?}, 0xc00034c0e0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd577c0?, 0xc0000fd220}, {0xed66f0, 0xc0002861e0}, 0xc000300540, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c8700, {0xed9f28, 0xc000456820}, 0xc00031e000, 0xc000335110, 0x14b8ae0, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0000c8700, {0xed9f28, 0xc000456820}, 0xc00031e000, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.47.0/server.go:920 +0x28a

Error: The terraform-provider-looker_v0.4.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior:** The resource after the plan has been confirmed should then create the alert in looker when the command `terraform apply` has been used rather than crashing.

**Comment by THolleyZen** [comment]
@cdmitri can I please get some help?
